version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      DATABASE_URL: '${DB_CONNECTION}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?authSource=admin'

  mongo:
    build:
      context: .
      dockerfile: ./docker/mongo.Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
      MONGO_REPLICA_HOST: ${DB_HOST}
      MONGO_REPLICA_PORT: ${DB_PORT}
    ports:
      - '27017:27017'

  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nest-api
